// This file was auto-generated by Fern from our API Definition.

import type * as Respeecher from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GenerationRequest } from "./GenerationRequest.js";
import { OutputFormat } from "./OutputFormat.js";

export const BytesGenerationRequest: core.serialization.ObjectSchema<
    serializers.tts.BytesGenerationRequest.Raw,
    Respeecher.tts.BytesGenerationRequest
> = core.serialization
    .object({
        outputFormat: core.serialization.property("output_format", OutputFormat.optional()),
    })
    .extend(GenerationRequest);

export declare namespace BytesGenerationRequest {
    export interface Raw extends GenerationRequest.Raw {
        output_format?: OutputFormat.Raw | null;
    }
}
