// This file was auto-generated by Fern from our API Definition.

import type * as Respeecher from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CancellationRequest: core.serialization.ObjectSchema<
    serializers.tts.CancellationRequest.Raw,
    Respeecher.tts.CancellationRequest
> = core.serialization.object({
    contextId: core.serialization.property("context_id", core.serialization.string()),
    cancel: core.serialization.booleanLiteral(true),
});

export declare namespace CancellationRequest {
    export interface Raw {
        context_id: string;
        cancel: true;
    }
}
