// This file was auto-generated by Fern from our API Definition.

import type * as Respeecher from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { StreamingGenerationRequest } from "./StreamingGenerationRequest.js";

export const ContextfulGenerationRequest: core.serialization.ObjectSchema<
    serializers.tts.ContextfulGenerationRequest.Raw,
    Respeecher.tts.ContextfulGenerationRequest
> = core.serialization
    .object({
        contextId: core.serialization.property("context_id", core.serialization.string()),
        continue: core.serialization.boolean().optional(),
    })
    .extend(StreamingGenerationRequest);

export declare namespace ContextfulGenerationRequest {
    export interface Raw extends StreamingGenerationRequest.Raw {
        context_id: string;
        continue?: boolean | null;
    }
}
