// This file was auto-generated by Fern from our API Definition.

import type * as Respeecher from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const Done: core.serialization.ObjectSchema<serializers.tts.Done.Raw, Respeecher.tts.Done> =
    core.serialization.object({
        contextId: core.serialization.property("context_id", core.serialization.string()),
    });

export declare namespace Done {
    export interface Raw {
        context_id: string;
    }
}
