/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Respeecher from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const Error_: core.serialization.ObjectSchema<serializers.tts.Error_.Raw, Respeecher.tts.Error_> =
    core.serialization.object({
        error: core.serialization.string(),
        statusCode: core.serialization.property("status_code", core.serialization.number()),
        contextId: core.serialization.property("context_id", core.serialization.string().optional()),
    });

export declare namespace Error_ {
    export interface Raw {
        error: string;
        status_code: number;
        context_id?: string | null;
    }
}
