/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Respeecher from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { Voice } from "./Voice.js";

export const GenerationRequest: core.serialization.ObjectSchema<
    serializers.tts.GenerationRequest.Raw,
    Respeecher.tts.GenerationRequest
> = core.serialization.object({
    transcript: core.serialization.string(),
    voice: Voice,
});

export declare namespace GenerationRequest {
    export interface Raw {
        transcript: string;
        voice: Voice.Raw;
    }
}
