/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Respeecher from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const OutputFormat: core.serialization.ObjectSchema<
    serializers.tts.OutputFormat.Raw,
    Respeecher.tts.OutputFormat
> = core.serialization.object({
    sampleRate: core.serialization.property("sample_rate", core.serialization.number().optional()),
});

export declare namespace OutputFormat {
    export interface Raw {
        sample_rate?: number | null;
    }
}
