// This file was auto-generated by Fern from our API Definition.

import type * as Respeecher from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { OutputFormat } from "./OutputFormat.js";
import { StreamingEncoding } from "./StreamingEncoding.js";

export const StreamingOutputFormat: core.serialization.ObjectSchema<
    serializers.tts.StreamingOutputFormat.Raw,
    Respeecher.tts.StreamingOutputFormat
> = core.serialization
    .object({
        encoding: StreamingEncoding.optional(),
    })
    .extend(OutputFormat);

export declare namespace StreamingOutputFormat {
    export interface Raw extends OutputFormat.Raw {
        encoding?: StreamingEncoding.Raw | null;
    }
}
