// This file was auto-generated by Fern from our API Definition.

import type * as Respeecher from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GenerationRequest } from "./GenerationRequest.js";
import { StreamingOutputFormat } from "./StreamingOutputFormat.js";

export const StreamingGenerationRequest: core.serialization.ObjectSchema<
    serializers.tts.StreamingGenerationRequest.Raw,
    Respeecher.tts.StreamingGenerationRequest
> = core.serialization
    .object({
        outputFormat: core.serialization.property("output_format", StreamingOutputFormat.optional()),
    })
    .extend(GenerationRequest);

export declare namespace StreamingGenerationRequest {
    export interface Raw extends GenerationRequest.Raw {
        output_format?: StreamingOutputFormat.Raw | null;
    }
}
