/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Respeecher from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const Voice: core.serialization.ObjectSchema<serializers.tts.Voice.Raw, Respeecher.tts.Voice> =
    core.serialization.object({
        id: core.serialization.string(),
    });

export declare namespace Voice {
    export interface Raw {
        id: string;
    }
}
