// This file was auto-generated by Fern from our API Definition.

export const Gender = {
    Female: "female",
    Male: "male",
} as const;
export type Gender = (typeof Gender)[keyof typeof Gender];
