/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Respeecher from "../../../index.js";

export interface Voice {
    id: string;
    gender?: Respeecher.Gender;
    accent?: string;
    age?: string;
}
