/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Respeecher from "../../../index.js";

export interface Voice {
    id: string;
    fullName?: string;
    gender?: Respeecher.Gender;
    accent?: string;
    age?: string;
    /** Default sampling params for this voice. See also [Sampling Params Guide](../tts/sampling-params-guide). */
    samplingParams?: Respeecher.SamplingParams;
}
