/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RespeecherApi from "../../../index.js";

export interface Voice {
    id: string;
    gender?: RespeecherApi.Gender;
    accent?: string;
    age?: string;
}
