// This file was auto-generated by Fern from our API Definition.

import type * as Respeecher from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Voice } from "../types/Voice.js";

export const Response: core.serialization.Schema<serializers.voices.list.Response.Raw, Respeecher.Voice[]> =
    core.serialization.list(Voice);

export declare namespace Response {
    export type Raw = Voice.Raw[];
}
