/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index.js";
import * as Respeecher from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import { Response } from "../../types/Response.js";

export const WebSocketSocketResponse: core.serialization.Schema<
    serializers.tts.WebSocketSocketResponse.Raw,
    Respeecher.tts.Response
> = core.serialization.undiscriminatedUnion([Response]);

export declare namespace WebSocketSocketResponse {
    export type Raw = Response.Raw;
}
