// This file was auto-generated by Fern from our API Definition.

export interface CancellationRequest {
    /** Use different context IDs for different generations over one WebSocket connection. */
    context_id: string;
    cancel: true;
}
