/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RespeecherApi from "../../../index.js";

export interface ContextfulChunk extends RespeecherApi.tts.Chunk {
    context_id: string;
}
