// This file was auto-generated by Fern from our API Definition.

import type * as Respeecher from "../../../index.js";

/**
 * @example
 *     {
 *         context_id: "abc",
 *         transcript: "Hello, World!",
 *         voice: {
 *             id: "samantha"
 *         }
 *     }
 */
export interface ContextfulGenerationRequest extends Respeecher.tts.StreamingGenerationRequest {
    /** Use different context IDs for different generations over one WebSocket connection. */
    context_id: string;
    /** Set to `true` for smooth prosody if text is streamed in chunks and this is not the last chunk. */
    continue?: boolean;
}
