/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Respeecher from "../../../index.js";

export interface ContextfulChunk extends Respeecher.tts.Chunk {
    contextId: string;
}
