// This file was auto-generated by Fern from our API Definition.

import type * as Respeecher from "../../../index.js";

export interface ContextfulChunk extends Respeecher.tts.Chunk {
    context_id: string;
}
