/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Respeecher from "../../../index.js";

/**
 * @example
 *     {
 *         contextId: "abc",
 *         transcript: "Hello, World!",
 *         voice: {
 *             id: "samantha"
 *         }
 *     }
 */
export interface ContextfulGenerationRequest extends Respeecher.tts.StreamingGenerationRequest {
    /** Use different context IDs for different generations over one WebSocket connection. */
    contextId: string;
    /** Set to `true` for smooth prosody if text is streamed in chunks and this is not the last chunk. */
    continue?: boolean;
}
