// This file was auto-generated by Fern from our API Definition.

import type * as Respeecher from "../../../index.js";

export interface GenerationRequest {
    /** Text for narration. */
    transcript: string;
    /** Voice for narration. */
    voice: Respeecher.tts.Voice;
}
