/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RespeecherApi from "../../../index.js";

export interface GenerationRequest {
    /** Text for narration. */
    transcript: string;
    /** Voice for narration. */
    voice: RespeecherApi.tts.Voice;
}
