/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RespeecherApi from "../../../index.js";

/**
 * @example
 *     {
 *         type: "chunk",
 *         context_id: "abc",
 *         data: "base64"
 *     }
 *
 * @example
 *     {
 *         type: "done",
 *         context_id: "abc"
 *     }
 */
export type Response =
    | RespeecherApi.tts.Response.Chunk
    | RespeecherApi.tts.Response.Done
    | RespeecherApi.tts.Response.Error_;

export namespace Response {
    export interface Chunk extends RespeecherApi.tts.ContextfulChunk {
        type: "chunk";
    }

    export interface Done extends RespeecherApi.tts.Done {
        type: "done";
    }

    export interface Error_ extends RespeecherApi.tts.Error_ {
        type: "error";
    }
}
