// This file was auto-generated by Fern from our API Definition.

import type * as Respeecher from "../../../index.js";

/**
 * @example
 *     {
 *         type: "chunk",
 *         context_id: "abc",
 *         data: "base64"
 *     }
 *
 * @example
 *     {
 *         type: "done",
 *         context_id: "abc"
 *     }
 */
export type Response = Respeecher.tts.Response.Chunk | Respeecher.tts.Response.Done | Respeecher.tts.Response.Error_;

export namespace Response {
    export interface Chunk extends Respeecher.tts.ContextfulChunk {
        type: "chunk";
    }

    export interface Done extends Respeecher.tts.Done {
        type: "done";
    }

    export interface Error_ extends Respeecher.tts.StreamingError {
        type: "error";
    }
}
