/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RespeecherApi from "../../../index.js";

export type ServerSentEvent = RespeecherApi.tts.ServerSentEvent.Chunk | RespeecherApi.tts.ServerSentEvent.Error_;

export namespace ServerSentEvent {
    export interface Chunk extends RespeecherApi.tts.Chunk {
        type: "chunk";
    }

    export interface Error_ extends RespeecherApi.tts.Error_ {
        type: "error";
    }
}
