// This file was auto-generated by Fern from our API Definition.

import type * as Respeecher from "../../../index.js";

export type ServerSentEvent = Respeecher.tts.ServerSentEvent.Chunk | Respeecher.tts.ServerSentEvent.Error_;

export namespace ServerSentEvent {
    export interface Chunk extends Respeecher.tts.Chunk {
        type: "chunk";
    }

    export interface Error_ extends Respeecher.tts.StreamingError {
        type: "error";
    }
}
