/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type StreamingEncoding = "pcm_f32le" | "pcm_s16le";
export const StreamingEncoding = {
    PcmF32Le: "pcm_f32le",
    PcmS16Le: "pcm_s16le",
} as const;
