// This file was auto-generated by Fern from our API Definition.

export const StreamingEncoding = {
    PcmF32Le: "pcm_f32le",
    PcmS16Le: "pcm_s16le",
    PcmMulaw: "pcm_mulaw",
} as const;
export type StreamingEncoding = (typeof StreamingEncoding)[keyof typeof StreamingEncoding];
