/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RespeecherApi from "../../../index.js";

/**
 * @example
 *     {
 *         transcript: "Hello, World!",
 *         voice: {
 *             id: "samantha"
 *         }
 *     }
 */
export interface StreamingGenerationRequest extends RespeecherApi.tts.GenerationRequest {
    /** Audio format specification. */
    output_format?: RespeecherApi.tts.StreamingOutputFormat;
}
