/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Respeecher from "../../../index.js";

export interface StreamingOutputFormat extends Respeecher.tts.OutputFormat {
    encoding?: Respeecher.tts.StreamingEncoding;
}
