/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface StreamingError {
    /** Error message. */
    error: string;
    /** HTTP status code most appropriate for this error. */
    statusCode: number;
    contextId?: string;
}
