/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RespeecherApi from "../../../index.js";

export interface StreamingOutputFormat extends RespeecherApi.tts.OutputFormat {
    encoding?: RespeecherApi.tts.StreamingEncoding;
}
