// This file was auto-generated by Fern from our API Definition.

import type * as Respeecher from "../../../index.js";

/**
 * @example
 *     {
 *         id: "samantha"
 *     }
 */
export interface Voice {
    id: string;
    /** Optional sampling params overrides. The defaults for this voice can be obtained through the [Voices](../voices/list#response.body.sampling_params) endpoint. See also [Sampling Params Guide](../tts/sampling-params-guide). */
    sampling_params?: Respeecher.SamplingParams;
}
