/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Respeecher from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const Gender: core.serialization.Schema<serializers.Gender.Raw, Respeecher.Gender> = core.serialization.enum_([
    "female",
    "male",
]);

export declare namespace Gender {
    export type Raw = "female" | "male";
}
