/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Respeecher from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { Gender } from "./Gender.js";
import { SamplingParams } from "./SamplingParams.js";

export const Voice: core.serialization.ObjectSchema<serializers.Voice.Raw, Respeecher.Voice> =
    core.serialization.object({
        id: core.serialization.string(),
        gender: Gender.optional(),
        accent: core.serialization.string().optional(),
        age: core.serialization.string().optional(),
        samplingParams: core.serialization.property("sampling_params", SamplingParams.optional()),
    });

export declare namespace Voice {
    export interface Raw {
        id: string;
        gender?: Gender.Raw | null;
        accent?: string | null;
        age?: string | null;
        sampling_params?: SamplingParams.Raw | null;
    }
}
