/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { RespeecherClient } from "../../src/Client";

describe("Voices", () => {
    test("List", async () => {
        const server = mockServerPool.createServer();
        const client = new RespeecherClient({
            apiKey: "test",
            environment: { base: server.baseUrl, ws: server.baseUrl },
        });

        const rawResponseBody = [
            { id: "samantha", gender: "female", accent: "American" },
            { id: "volodymyr", gender: "male", accent: "Ukrainian" },
        ];
        server.mockEndpoint().get("/voices").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.voices.list();
        expect(response).toEqual([
            {
                id: "samantha",
                gender: "female",
                accent: "American",
            },
            {
                id: "volodymyr",
                gender: "male",
                accent: "Ukrainian",
            },
        ]);
    });
});
