// This file was auto-generated by Fern from our API Definition.

import { TtsClient } from "./api/resources/tts/client/Client.js";
import { VoicesClient } from "./api/resources/voices/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace RespeecherClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class RespeecherClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<RespeecherClient.Options>;
    protected _tts: TtsClient | undefined;
    protected _voices: VoicesClient | undefined;

    constructor(options: RespeecherClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get tts(): TtsClient {
        return (this._tts ??= new TtsClient(this._options));
    }

    public get voices(): VoicesClient {
        return (this._voices ??= new VoicesClient(this._options));
    }
}
