// This file was auto-generated by Fern from our API Definition.

export interface RespeecherEnvironmentUrls {
    base: string;
    ws: string;
}

export const RespeecherEnvironment = {
    PublicEnRt: {
        base: "https://api.respeecher.com/v1/public/tts/en-rt",
        ws: "wss://api.respeecher.com/v1/public/tts/en-rt",
    },
    PublicUaRt: {
        base: "https://api.respeecher.com/v1/public/tts/ua-rt",
        ws: "wss://api.respeecher.com/v1/public/tts/ua-rt",
    },
} as const;

export type RespeecherEnvironment = typeof RespeecherEnvironment.PublicEnRt | typeof RespeecherEnvironment.PublicUaRt;
