/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RespeecherApiEnvironmentUrls {
    base: string;
    ws: string;
}

export const RespeecherApiEnvironment = {
    PublicEnRt: {
        base: "https://api.respeecher.com/v1/public/tts/en-rt",
        ws: "wss://api.respeecher.com/v1/public/tts/en-rt",
    },
} as const;

export type RespeecherApiEnvironment = typeof RespeecherApiEnvironment.PublicEnRt;
